defaults: &defaults
  working_directory: /react-day-picker
  docker:
      - image: node:7.10.0
        environment:
          TEST_REPORT_PATH: "reports"

version: 2
    
jobs:
  checkout-and-test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: cache-project-v1-{{ checksum "yarn.lock" }}
      - run: yarn --pure-lockfile
      - save_cache:
          key: cache-project-v1-{{ checksum "yarn.lock" }}
          paths:
            - "/usr/local/share/.cache/yarn"
            - "./node_modules"
      - run: yarn lint -- --format junit --output-file reports/eslint.xml
      - run: yarn dtslint
      - run: yarn test -- --coverage --testResultsProcessor jest-junit-reporter
      - run: yarn codecov
      - persist_to_workspace:
          root: .
      
  build-project: 
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: yarn build

  build-docs:
    working_directory: ~/react-day-picker
    docker:
      - image: circleci/ruby:2.4.1-node
    steps:
      - checkout
      - restore_cache:
          key: cache-docs-{{ checksum "docs/Gemfile.lock" }}
      - run: npm install gh-pages
      - run: |
          cd docs
          bundle install
       # Store bundle cache
      - save_cache:
          key: cache-docs-{{ checksum "docs/Gemfile.lock" }}
          paths:
            - "/usr/local/bundle"
            - "./node_modules"
      - run: |
          cd docs
          bundle exec jekyll build
      - run: |
          git config --global user.email "$GH_EMAIL" > /dev/null 2>&1 
          git config --global user.name "$GH_NAME" > /dev/null 2>&1
      - run: npm run docs:publish

workflows:
  version: 2
  build:
    jobs:
      - checkout-and-test
      - build-project:
          requires: 
            - checkout-and-test
          filters:
            branches:
              only: master   
      - build-docs:
          filters:
            branches:
              only: master   
