include:
- ../README.md

title: react-day-picker
email: your-email@domain.com
description:
  react-day-picker is a flexible and customizable date picker component 
  for React. Select days, ranges, whatever using modifiers. Simple 
  localization. Navigable with keyboard. ARIA support.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://react-day-picker.js.org/"

markdown: kramdown
kramdown:
    input: GFM 
    syntax_highlighter: rouge
highlighter: rouge

sass:
  style: :compressed
  sass_dir: _css

gems:
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-autoprefixer

lib_version: 6.1.0
exclude:
  - Gemfile
  - Gemfile.lock
