name: performance

on:
  pull_request:
    types: [labeled, synchronize, opened]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'performance')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm

      - name: Create pnpm store directory
        run: mkdir -p ~/.pnpm-store

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rdp-dist
          path: dist

  run:
    if: contains(github.event.pull_request.labels.*.name, 'performance')
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        id: setup-chrome

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: rdp-dist
          path: dist

      - name: Create pnpm store directory
        run: mkdir -p ~/.pnpm-store

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Start server
        run: pnpm --filter performance-tests start-server &
        env:
          CHROME_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}

      - name: Wait for server to start
        run: pnpx wait-on http://localhost:4173 --timeout 10000

      - name: Capture performance test
        run: pnpm --filter performance-tests run capture
        env:
          CHROME_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
          CI: true

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: ./performance-tests/reports/report.html

      - name: Upload markdown report
        uses: actions/upload-artifact@v4
        with:
          name: markdown-report
          path: ./performance-tests/reports/markdown-report.md

  post-comment:
    if: contains(github.event.pull_request.labels.*.name, 'performance')
    needs: [run]
    runs-on: ubuntu-latest
    steps:
      - name: Download markdown report
        uses: actions/download-artifact@v4
        with:
          name: markdown-report
          path: ./markdown-report

      - name: Read markdown report
        id: read-markdown
        run: |
          markdown_content=$(cat ./markdown-report/markdown-report.md)
          echo "markdown_content<<EOF" >> $GITHUB_ENV
          echo "$markdown_content" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Post comment with download link and markdown content
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const artifactUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            const markdownContent = process.env.markdown_content;
            const comment = `Performance test reports are available [here](${artifactUrl}).\n\n### Markdown Report:\n\n${markdownContent}`;
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: comment
            });
