name: "CI: publish"

on:
  push:
    tags:
      - v8.*

jobs:
  test-build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Get version name
        id: get-tag-name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v1
        with:
          ref: ${{ steps.get-tag-name.outputs.VERSION }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-cache-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            yarn-cache-${{ hashFiles('./yarn.lock') }}

      - name: Install Dependencies
        run: yarn install

      - name: Lint Files
        run: yarn lint --coverage
        working-directory: ./packages/react-day-picker

      - name: Run Unit Tests
        run: yarn test
        working-directory: ./packages/react-day-picker

      - name: Build
        run: yarn build
        working-directory: ./packages/react-day-picker

      - name: Publish on npm
        run: npm publish --tag next
        working-directory: ./packages/react-day-picker
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
