name: npm-publish

on:
  release:
    types: [created]
  push:
    branches:
      - master
    paths:
      - "packages/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run typecheck (react-day-picker)
        run: yarn workspace react-day-picker run typecheck
      - name: Run lint (react-day-picker)
        run: yarn workspace react-day-picker run lint --max-warnings 0
      - name: Run test (react-day-picker)
        run: yarn workspace react-day-picker run test

  test-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run build (react-day-picker)
        run: yarn workspace react-day-picker run build
      - name: Run typecheck (website)
        run: yarn workspace website run typecheck
      - name: Run test (website)
        run: yarn workspace website run test

  pre-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'))
    needs: [test-website, test]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.get-tag-name.outputs.VERSION }}
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run build (react-day-picker)
        run: yarn workspace react-day-picker run build
      - name: Publish package (@next)
        working-directory: packages/react-day-picker
        run: |
          echo ${{ secrets.NPM_TOKEN }} >> .npmrc
          yarn publish --tag next

  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    needs: [test-website, test]
    steps:
      - name: Get version name
        id: get-tag-name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.get-tag-name.outputs.VERSION }}
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable

      - name: Run build (react-day-picker)
        run: yarn workspace react-day-picker run build

      - name: Publish package
        working-directory: packages/react-day-picker
        run: |
          echo ${{ secrets.NPM_TOKEN }} >> .npmrc
          yarn publish

  deploy-website:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'release' || github.event_name == 'workflow_dispatch'
    needs: [pre-release, release]
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Install dependencies
        run: |
          yarn install --immutable
          yarn add react-day-picker@latest
      - name: Build website
        run: |
          yarn workspace website build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
