name: "CI: website-deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "!packages/**"

jobs:
  lint-test-typecheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.14]
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@HEAD
      - name: Run typecheck
        run: |
          yarn workspace website run typecheck
      - name: Run linter
        run: |
          yarn workspace website run lint --max-warnings 0
      - name: Run integration tests
        run: |
          yarn workspace website run test
      - name: Deploy website
        run: |
          yarn workspace website run Deploy
  deploy:
    runs-on: ubuntu-latest
    needs: lint-test-typecheck
    strategy:
      matrix:
        node-version: [16.14]
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@HEAD
      - name: Deploy website
        run: |
          yarn workspace website run deploy
